const mock_services_banks = [{ "bankId": 1,
                    "name": "Raiffeisen",
                    "logo": "",
                    "swift": "82b92c",
                    "clearing": "12345",
                    "address": "test",
                    "postalCode":"1234",
                    "locality": "Lugano",
                    "country": "Hello World",
                    "createdAt": "Hello World",
                    "updatedAt": "Hello World"
                    },
                    {
                    "bankId": 2,
                    "name": "UBS",
                    "logo": "",
                    "swift": "64532",
                    "clearing": "53421",
                    "address": "tet2",
                    "postalCode":"1234",
                    "locality": "Lugano",
                    "country": "Svizzera",
                    "createdAt": "Hello World",
                    "updatedAt": "Hello World"
                    }];
